use signal_lojix::{LOJIX_INTERFACE_RUST, LOJIX_INTERFACE_SOURCE, bootstrap_manifest};

#[test]
fn canonical_source_is_role_free_types_only_bootstrap_interface() {
    assert!(LOJIX_INTERFACE_SOURCE.starts_with("Interface.{1 0 0}\n[]\n{\n  []\n  []\n  []\n  ["));
    assert!(LOJIX_INTERFACE_SOURCE.contains("OrdinaryRequest.["));
    assert!(LOJIX_INTERFACE_SOURCE.contains("OrdinaryReply.["));
    assert!(!LOJIX_INTERFACE_SOURCE.contains("Optional."));
}

#[test]
fn strict_rust_projection_uses_only_encoded_object_coordinates() {
    assert!(LOJIX_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n"
    ));
    for visible in ["OrdinaryRequest", "OrdinaryReply", "DeploymentRecord"] {
        assert!(!LOJIX_INTERFACE_RUST.contains(&format!("pub enum {visible}")));
        assert!(!LOJIX_INTERFACE_RUST.contains(&format!("pub struct {visible}")));
    }
    assert!(bootstrap_manifest::DECLARATION_SEATS.len() > 100);
}

#[test]
fn retired_schema_source_directory_is_absent() {
    let crate_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    assert!(!crate_root.join("schema").exists());
    assert!(crate_root.join("ethos/lib.ethos").is_file());
}
