// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2VbPz {z2VRmx , z2VLoi , z2VUoE ,} 
pub struct z2VLkY ( z2VKvY ,) ;
pub enum z2VcR1 {z2VS1B ( z2VcB9 ,) , z2VQom ( z2VUqu ,) , z2VaL5 ( z2VRxu ,) , z2VZdT ( z2VNmE ,) , z2Vby6 ( z2Vb9C ,) , z2VZXM ( z2VW5R ,) , z2VYcX ( z2VRhr ,) , z2VNFq ( z2Ve15 ,) , z2VVBd ( z2VWof ,) , z2VNoL ( z2VUAE ,) ,} 
pub struct z2VU8F(u64);
impl z2VU8F {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VTki {z2VLTU , z2VVvC , z2Vbgy , z2Va9j , z2VdwX , z2VUZc ,} 
pub struct z2VR89(u64);
impl z2VR89 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VRZj {
    pub field_0: z2Vdkm,
    pub field_1: z2VU8F,
    pub field_2: z2VXtV,
    pub field_3: z2VXGN,
    pub field_4: z2VVG2,
    pub field_5: z2VPWn,
    pub field_6: z2Vchw,
    pub field_7: Option<z2VQbS>,
    pub field_8: Option<z2VZQW>,
}
pub struct z2VY5C {
    pub field_0: Option<z2Vdkm>,
    pub field_1: Option<z2VXtV>,
    pub field_2: Option<z2VXGN>,
}
pub struct z2VUAE ( z2VdhM ,) ;
pub struct z2VYbZ(std::string::String);
impl z2VYbZ {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VNmE ( z2VeXy ,) ;
pub enum z2VYJj {z2VdtZ ( z2VZH3 ,) , z2VbKj ( z2VbPz ,) ,} 
pub struct z2VXGN(std::string::String);
impl z2VXGN {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VRxu ( z2VSEh ,) ;
pub struct z2VSEh {
    pub field_0: z2VcoS,
    pub field_1: z2VaUx,
}
pub struct z2VZQZ {
    pub field_0: z2VU8F,
}
pub enum z2VNtH {z2VTqM ( z2VWkd ,) , z2VaJP , z2VQCt ,} 
pub enum z2VZ35 {z2Vbes , z2VcDV , z2VNZE ,} 
pub struct z2VYYM {
    pub field_0: z2VZ35,
    pub field_1: z2VQsT,
    pub field_2: z2VQsT,
    pub field_3: z2VMfj,
}
pub enum z2VSLz {z2VYQz , z2VaPL , z2VQZj , z2VPBA ,} 
pub struct z2VTjL {
    pub field_0: z2VXtV,
    pub field_1: z2VXGN,
    pub field_2: Option<z2VNzL>,
}
pub struct z2VYRj(u64);
impl z2VYRj {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VaCk(std::string::String);
impl z2VaCk {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Vbti {
    pub field_0: z2Vdkm,
    pub field_1: z2VU8F,
    pub field_2: z2VaQR,
    pub field_3: Option<z2VSfk>,
    pub field_4: z2VSVX,
    pub field_5: Option<z2VW3Q>,
    pub field_6: Option<z2VZQW>,
}
pub struct z2Ve15 ( z2VZWT ,) ;
pub enum z2VWkd {z2VNRB , z2VZrd , z2VWp7 , z2VUtp , z2VdmZ ,} 
pub struct z2VYpD {
    pub field_0: z2VNzL,
    pub field_1: z2VXtV,
    pub field_2: z2VXGN,
    pub field_3: z2VXGN,
    pub field_4: z2VKsi,
    pub field_5: z2VPhf,
    pub field_6: z2VNtH,
    pub field_7: Option<z2VTGR>,
}
pub enum z2VZH3 {z2VUJK , z2Ve1w , z2VZeG , z2VNyd , z2VRtT , z2Vapv ,} 
pub struct z2VMFV(std::string::String);
impl z2VMFV {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VTQ9 {
    pub field_0: Vec<z2VZx1>,
    pub field_1: Vec<z2Vbti>,
    pub field_2: z2VaUx,
}
pub struct z2VLsn {
    pub field_0: z2Vdkm,
}
pub struct z2VX97 ( z2VY5C ,) ;
pub enum z2VRgR {z2Vdj3 , z2VYqF ,} 
pub enum z2VVKC {z2VLpz , z2VTwD , z2VNs9 , z2VeUT , z2VUaC ,} 
pub struct z2VNzL(u64);
impl z2VNzL {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VQsT(std::string::String);
impl z2VQsT {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VU8v {z2VYNa , z2VQ5p ,} 
pub struct z2VKvY {
    pub field_0: Option<z2VXtV>,
    pub field_1: Option<z2VXGN>,
}
pub struct z2VVJv(std::string::String);
impl z2VVJv {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VVG2 {z2VYWx , z2VPKd , z2VTfm , z2VXsR , z2VRQP , z2VPgL , z2VbX9 , z2VQYT , z2VP98 ,} 
pub struct z2VaUx {
    pub field_0: z2VR89,
    pub field_1: z2VebC,
}
pub struct z2VSfk ( z2VaUx ,) ;
pub struct z2VSgN(std::string::String);
impl z2VSgN {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VXcT(std::string::String);
impl z2VXcT {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Vb9C ( z2Vdhd ,) ;
pub struct z2VaQR {
    pub field_0: z2VWUZ,
    pub field_1: z2VXtV,
    pub field_2: z2VXGN,
    pub field_3: z2Vccx,
    pub field_4: z2VYJj,
    pub field_5: z2VSJr,
    pub field_6: z2VLic,
    pub field_7: Option<z2VQbS>,
}
pub struct z2VXQc ( z2Vcmr ,) ;
pub struct z2Vchw ( z2VaUx ,) ;
pub struct z2VbSz {
    pub field_0: z2VXGN,
    pub field_1: Vec<z2VYYM>,
    pub field_2: z2VaUx,
}
pub struct z2VaWM {
    pub field_0: z2VXtV,
    pub field_1: z2VXGN,
    pub field_2: Option<z2VSqw>,
}
pub struct z2VPWn(u64);
impl z2VPWn {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VdhM {
    pub field_0: z2VSSW,
}
pub struct z2VUnY {
    pub field_0: z2VU8F,
    pub field_1: z2VXtV,
    pub field_2: z2VXGN,
    pub field_3: z2VTki,
    pub field_4: z2VVKC,
    pub field_5: Option<z2VVKC>,
    pub field_6: Option<z2VMFV>,
    pub field_7: z2VPWn,
}
pub struct z2VatQ(std::string::String);
impl z2VatQ {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VQgC {z2VNUJ , z2VXMh ,} 
pub enum z2VPhf {z2VZSx , z2VQnr , z2VPeJ , z2Vc2g , z2VZRE , z2VP1f , z2Vd9o ,} 
pub struct z2VcB9 ( z2VWhZ ,) ;
pub struct z2VUqu ( z2VWjn ,) ;
pub struct z2VSn8 {
    pub field_0: z2VSDa,
    pub field_1: z2VSgN,
}
pub struct z2VL3w {
    pub field_0: z2VKsi,
    pub field_1: z2VaCk,
    pub field_2: z2VXma,
    pub field_3: Option<z2VSn8>,
}
pub struct z2VeXy {
    pub field_0: z2VYRj,
    pub field_1: z2VR89,
}
pub enum z2VSSW {z2VdBQ , z2Vdtn , z2VNsZ ,} 
pub enum z2VWva {z2VN5x , z2VWX7 ,} 
pub enum z2Vccx {z2VKxg , z2VSDK , z2Vdt1 ,} 
pub struct z2VWof ( z2VbSz ,) ;
pub struct z2VWjn {
    pub field_0: z2VRgR,
    pub field_1: z2VYRj,
}
pub struct z2VNia {
    pub field_0: Vec<z2VRZj>,
    pub field_1: Vec<z2VUnY>,
    pub field_2: z2VaUx,
}
pub struct z2VZ95 {
    pub field_0: z2VYRj,
}
pub struct z2VW3Q ( z2VaUx ,) ;
pub enum z2VWUZ {z2VR5a , z2VWiX ( z2VXcT ,) ,} 
pub struct z2VQbS(std::string::String);
impl z2VQbS {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VcE8 ( z2VZ95 ,) ;
pub enum z2Vbmn {z2VZES ( z2VXGN ,) , z2VPV4 ,} 
pub struct z2VYDb {
    pub field_0: z2VPWn,
    pub field_1: z2VPWn,
}
pub enum z2VSVX {z2VPDe , z2VWHo , z2VZDJ , z2VaaD , z2VeS7 , z2VdRe , z2Vecz , z2VToU , z2VZH5 ,} 
pub struct z2VXma {
    pub field_0: z2VVJv,
}
pub struct z2VTGR(std::string::String);
impl z2VTGR {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VSJr {z2Vbim , z2VM1U , z2VWyK , z2VP6k , z2VeUe ,} 
pub struct z2VZWT {
    pub field_0: z2VYRj,
}
pub struct z2VeF3 ( z2VZdM ,) ;
pub enum z2VTvQ {z2VbbV ( z2VeF3 ,) , z2VdkL ( z2VX97 ,) , z2VTeG ( z2VXQc ,) , z2VZpJ ( z2VLkY ,) , z2VUL5 ( z2VcE8 ,) ,} 
pub enum z2VKsi {z2VdnZ , z2VP1x ,} 
pub struct z2VebC(u64);
impl z2VebC {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VcoS {z2VbqN , z2VXYu , z2VYjx , z2VV4Q ,} 
pub struct z2VSDa(std::string::String);
impl z2VSDa {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWhZ {
    pub field_0: Vec<z2VYpD>,
    pub field_1: z2VaUx,
}
pub enum z2VZQW {z2VRVE ( z2Vdph ,) , z2VTCC ( z2VYo6 ,) , z2VciR ,} 
pub enum z2VLic {z2Ve6d , z2VRE9 ,} 
pub struct z2VZdM {
    pub field_0: z2VXtV,
    pub field_1: z2VXGN,
    pub field_2: z2VYbZ,
}
pub struct z2VXtV(std::string::String);
impl z2VXtV {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VMfj(std::string::String);
impl z2VMfj {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Vdkm(u64);
impl z2Vdkm {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VSqw {z2VdBP , z2VafE , z2VNtW ,} 
pub struct z2VRhr ( z2VNia ,) ;
pub struct z2Vdph {
    pub field_0: z2VQSr,
    pub field_1: z2VYo6,
}
pub enum z2VQSr {z2VezU , z2VUaL , z2VMxu , z2VW1w , z2VUAR , z2VTcL , z2VWuE , z2VWKC ,} 
pub struct z2VZx1 {
    pub field_0: z2VU8F,
    pub field_1: z2Vdkm,
    pub field_2: z2VXtV,
    pub field_3: z2VXGN,
    pub field_4: z2Vccx,
    pub field_5: z2VSJr,
    pub field_6: z2VVKC,
    pub field_7: Option<z2VTGR>,
    pub field_8: Option<z2VQbS>,
}
pub struct z2VW5R ( z2VTQ9 ,) ;
pub struct z2Vdhd {
    pub field_0: z2VSLz,
    pub field_1: z2VaUx,
}
pub struct z2VXKF(std::string::String);
impl z2VXKF {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VYo6 {z2VW8n , z2Vb5u , z2VQVZ , z2VXt6 , z2VMwr , z2VYUu , z2VdC4 , z2VYvX , z2VTKv , z2VcLy , z2VbxC ,} 
pub enum z2Vcmr {z2VSAw ( z2VaWM ,) , z2VXA6 ( z2VTjL ,) , z2VS4H ( z2VLsn ,) , z2VWXq ( z2VZQZ ,) , z2VUAB ( z2VYDb ,) ,} 
