// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

pub type Query = Selection;

pub type WatchDeployments = DeploymentWatch;

pub type WatchCacheRetention = CacheRetentionWatch;

pub type Unwatch = SubscriptionClose;

pub type CheckHostKeyMaterial = KeyMaterialQuery;

pub type Queried = GenerationListing;

pub type Watching = SubscriptionOpened;

pub type Unwatched = SubscriptionClosed;

pub type KeyMaterialChecked = KeyMaterialReport;

pub type QueryRejected = RejectedQuery;

pub type WatchRejected = RejectedWatch;

pub type UnwatchRejected = RejectedUnwatch;

pub type KeyMaterialCheckRejected = RejectedKeyMaterialCheck;

pub type DeploymentIdentifier = Integer;

pub type GenerationIdentifier = Integer;

pub type SubscriptionToken = Integer;

pub type CommitSequence = Integer;

pub type StateDigest = Integer;

pub type ClusterName = String;

pub type NodeName = String;

pub type UserName = String;

pub type ClosurePath = String;

pub type ProposalSource = String;

pub type FlakeReference = String;

pub type EventLogPosition = Integer;

pub type PinLabel = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeploymentKind {
    FullOs,
    OsOnly,
    HomeOnly,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SystemAction {
    Eval,
    Build,
    Boot,
    Switch,
    Test,
    BootOnce,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ActivationKind {
    Switch,
    Boot,
    Test,
    BootOnce,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum GenerationSlot {
    Current,
    BootPending,
    Rollback,
    Pinned,
    Recent,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Generation {
    pub generation_identifier: GenerationIdentifier,
    pub deployment_identifier: DeploymentIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub deployment_kind: DeploymentKind,
    pub activation_kind: ActivationKind,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GenerationListing {
    pub generations: Vec<Generation>,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NodeSelector {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub kind: Option<DeploymentKind>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GenerationLookup(pub GenerationIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogRange {
    pub from: EventLogPosition,
    pub until: EventLogPosition,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Selection {
    ByNode(NodeSelector),
    ByGeneration(GenerationLookup),
    ByEventLog(EventLogRange),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeploymentWatch {
    pub deployment: Option<DeploymentIdentifier>,
    pub cluster: Option<ClusterName>,
    pub node: Option<NodeName>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CacheRetentionWatch {
    pub cluster: Option<ClusterName>,
    pub node: Option<NodeName>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionClose(pub SubscriptionToken);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionOpened {
    pub subscription_token: SubscriptionToken,
    pub commit_sequence: CommitSequence,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionClosed(pub SubscriptionToken);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KeyMaterialQuery {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub source: ProposalSource,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum KeyMaterialConcern {
    SecureShellPublicKey,
    YggdrasilPublicKey,
    YggdrasilAddress,
}

pub type MismatchValue = String;

pub type OperatorHint = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KeyMaterialMismatch {
    pub key_material_concern: KeyMaterialConcern,
    pub expected: MismatchValue,
    pub actual: MismatchValue,
    pub operator_hint: OperatorHint,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KeyMaterialReport {
    pub node_name: NodeName,
    pub mismatches: Vec<KeyMaterialMismatch>,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeploymentPhase {
    Submitted,
    Building,
    Built,
    Copying,
    Activating,
    Activated,
    Failed,
}

pub type PhaseDetail = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeploymentPhaseEvent {
    pub deployment_identifier: DeploymentIdentifier,
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub deployment_phase: DeploymentPhase,
    pub event_log_position: EventLogPosition,
    pub detail: Option<PhaseDetail>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CacheRetentionTransition {
    Pinned,
    Unpinned,
    Promoted,
    Demoted,
    Retired,
    Evicted,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CacheRetentionTransitionEvent {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub cache_retention_transition: CacheRetentionTransition,
    pub from_slot: GenerationSlot,
    pub to_slot: Option<GenerationSlot>,
    pub label: Option<PinLabel>,
    pub event_log_position: EventLogPosition,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum QueryRejectionReason {
    GenerationUnknown,
    NodeUnknown,
    EventLogPositionOutOfRange,
    MalformedSelector,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WatchRejectionReason {
    SubscriptionLimitReached,
    MalformedWatch,
    StreamUnavailable,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum UnwatchRejectionReason {
    SubscriptionTokenUnknown,
    SubscriptionAlreadyClosed,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum KeyMaterialCheckRejectionReason {
    NodeUnknown,
    ProposalSourceUnreachable,
    HostUnreachable,
    PublicationMalformed,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedQuery {
    pub query_rejection_reason: QueryRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedWatch(pub WatchRejectionReason);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedUnwatch {
    pub unwatch_rejection_reason: UnwatchRejectionReason,
    pub subscription_token: SubscriptionToken,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedKeyMaterialCheck {
    pub key_material_check_rejection_reason: KeyMaterialCheckRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Query(Query),
    WatchDeployments(WatchDeployments),
    WatchCacheRetention(WatchCacheRetention),
    Unwatch(Unwatch),
    CheckHostKeyMaterial(CheckHostKeyMaterial),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Queried(Queried),
    Watching(Watching),
    Unwatched(Unwatched),
    KeyMaterialChecked(KeyMaterialChecked),
    QueryRejected(QueryRejected),
    WatchRejected(WatchRejected),
    UnwatchRejected(UnwatchRejected),
    KeyMaterialCheckRejected(KeyMaterialCheckRejected),
}

impl GenerationLookup {
    pub fn new(payload: GenerationIdentifier) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &GenerationIdentifier {
        &self.0
    }

    pub fn into_payload(self) -> GenerationIdentifier {
        self.0
    }
}

impl From<GenerationIdentifier> for GenerationLookup {
    fn from(payload: GenerationIdentifier) -> Self {
        Self::new(payload)
    }
}

impl SubscriptionClose {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }

    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}

impl From<SubscriptionToken> for SubscriptionClose {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

impl SubscriptionClosed {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }

    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}

impl From<SubscriptionToken> for SubscriptionClosed {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

impl RejectedWatch {
    pub fn new(payload: WatchRejectionReason) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &WatchRejectionReason {
        &self.0
    }

    pub fn into_payload(self) -> WatchRejectionReason {
        self.0
    }
}

impl From<WatchRejectionReason> for RejectedWatch {
    fn from(payload: WatchRejectionReason) -> Self {
        Self::new(payload)
    }
}

impl Selection {
    pub fn by_node(payload: NodeSelector) -> Self {
        Self::ByNode(payload)
    }

    pub fn by_generation(payload: GenerationIdentifier) -> Self {
        Self::ByGeneration(GenerationLookup::new(payload))
    }

    pub fn by_event_log(payload: EventLogRange) -> Self {
        Self::ByEventLog(payload)
    }
}

impl Input {
    pub fn query(payload: Query) -> Self {
        Self::Query(payload)
    }

    pub fn watch_deployments(payload: WatchDeployments) -> Self {
        Self::WatchDeployments(payload)
    }

    pub fn watch_cache_retention(payload: WatchCacheRetention) -> Self {
        Self::WatchCacheRetention(payload)
    }

    pub fn unwatch(payload: Unwatch) -> Self {
        Self::Unwatch(payload)
    }

    pub fn check_host_key_material(payload: CheckHostKeyMaterial) -> Self {
        Self::CheckHostKeyMaterial(payload)
    }
}

impl Output {
    pub fn queried(payload: Queried) -> Self {
        Self::Queried(payload)
    }

    pub fn watching(payload: Watching) -> Self {
        Self::Watching(payload)
    }

    pub fn unwatched(payload: Unwatched) -> Self {
        Self::Unwatched(payload)
    }

    pub fn key_material_checked(payload: KeyMaterialChecked) -> Self {
        Self::KeyMaterialChecked(payload)
    }

    pub fn query_rejected(payload: QueryRejected) -> Self {
        Self::QueryRejected(payload)
    }

    pub fn watch_rejected(payload: WatchRejected) -> Self {
        Self::WatchRejected(payload)
    }

    pub fn unwatch_rejected(payload: UnwatchRejected) -> Self {
        Self::UnwatchRejected(payload)
    }

    pub fn key_material_check_rejected(payload: KeyMaterialCheckRejected) -> Self {
        Self::KeyMaterialCheckRejected(payload)
    }
}

impl From<NodeSelector> for Selection {
    fn from(payload: NodeSelector) -> Self {
        Self::ByNode(payload)
    }
}

impl From<GenerationLookup> for Selection {
    fn from(payload: GenerationLookup) -> Self {
        Self::ByGeneration(payload)
    }
}

impl From<EventLogRange> for Selection {
    fn from(payload: EventLogRange) -> Self {
        Self::ByEventLog(payload)
    }
}

#[cfg(feature = "nota-text")]
impl DeploymentKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SystemAction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ActivationKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl GenerationSlot {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DatabaseMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Generation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl GenerationListing {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NodeSelector {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl GenerationLookup {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EventLogRange {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Selection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DeploymentWatch {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CacheRetentionWatch {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SubscriptionClose {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SubscriptionOpened {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SubscriptionClosed {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl KeyMaterialQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl KeyMaterialConcern {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl KeyMaterialMismatch {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl KeyMaterialReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DeploymentPhase {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DeploymentPhaseEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CacheRetentionTransition {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CacheRetentionTransitionEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl QueryRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl WatchRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl UnwatchRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl KeyMaterialCheckRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectedQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectedWatch {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectedUnwatch {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectedKeyMaterialCheck {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_QUERY: u64 = 0x0000000000000000;
    pub const INPUT_WATCH_DEPLOYMENTS: u64 = 0x0001000000000000;
    pub const INPUT_WATCH_CACHE_RETENTION: u64 = 0x0002000000000000;
    pub const INPUT_UNWATCH: u64 = 0x0003000000000000;
    pub const INPUT_CHECK_HOST_KEY_MATERIAL: u64 = 0x0004000000000000;
    pub const OUTPUT_QUERIED: u64 = 0x0100000000000000;
    pub const OUTPUT_WATCHING: u64 = 0x0101000000000000;
    pub const OUTPUT_UNWATCHED: u64 = 0x0102000000000000;
    pub const OUTPUT_KEY_MATERIAL_CHECKED: u64 = 0x0103000000000000;
    pub const OUTPUT_QUERY_REJECTED: u64 = 0x0104000000000000;
    pub const OUTPUT_WATCH_REJECTED: u64 = 0x0105000000000000;
    pub const OUTPUT_UNWATCH_REJECTED: u64 = 0x0106000000000000;
    pub const OUTPUT_KEY_MATERIAL_CHECK_REJECTED: u64 = 0x0107000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    Query,
    WatchDeployments,
    WatchCacheRetention,
    Unwatch,
    CheckHostKeyMaterial,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    Queried,
    Watching,
    Unwatched,
    KeyMaterialChecked,
    QueryRejected,
    WatchRejected,
    UnwatchRejected,
    KeyMaterialCheckRejected,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Query(_) => InputRoute::Query,
            Self::WatchDeployments(_) => InputRoute::WatchDeployments,
            Self::WatchCacheRetention(_) => InputRoute::WatchCacheRetention,
            Self::Unwatch(_) => InputRoute::Unwatch,
            Self::CheckHostKeyMaterial(_) => InputRoute::CheckHostKeyMaterial,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::WatchDeployments(_) => short_header::INPUT_WATCH_DEPLOYMENTS,
            Self::WatchCacheRetention(_) => short_header::INPUT_WATCH_CACHE_RETENTION,
            Self::Unwatch(_) => short_header::INPUT_UNWATCH,
            Self::CheckHostKeyMaterial(_) => short_header::INPUT_CHECK_HOST_KEY_MATERIAL,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_QUERY => Ok(InputRoute::Query),
            short_header::INPUT_WATCH_DEPLOYMENTS => Ok(InputRoute::WatchDeployments),
            short_header::INPUT_WATCH_CACHE_RETENTION => Ok(InputRoute::WatchCacheRetention),
            short_header::INPUT_UNWATCH => Ok(InputRoute::Unwatch),
            short_header::INPUT_CHECK_HOST_KEY_MATERIAL => Ok(InputRoute::CheckHostKeyMaterial),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Queried(_) => OutputRoute::Queried,
            Self::Watching(_) => OutputRoute::Watching,
            Self::Unwatched(_) => OutputRoute::Unwatched,
            Self::KeyMaterialChecked(_) => OutputRoute::KeyMaterialChecked,
            Self::QueryRejected(_) => OutputRoute::QueryRejected,
            Self::WatchRejected(_) => OutputRoute::WatchRejected,
            Self::UnwatchRejected(_) => OutputRoute::UnwatchRejected,
            Self::KeyMaterialCheckRejected(_) => OutputRoute::KeyMaterialCheckRejected,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Queried(_) => short_header::OUTPUT_QUERIED,
            Self::Watching(_) => short_header::OUTPUT_WATCHING,
            Self::Unwatched(_) => short_header::OUTPUT_UNWATCHED,
            Self::KeyMaterialChecked(_) => short_header::OUTPUT_KEY_MATERIAL_CHECKED,
            Self::QueryRejected(_) => short_header::OUTPUT_QUERY_REJECTED,
            Self::WatchRejected(_) => short_header::OUTPUT_WATCH_REJECTED,
            Self::UnwatchRejected(_) => short_header::OUTPUT_UNWATCH_REJECTED,
            Self::KeyMaterialCheckRejected(_) => short_header::OUTPUT_KEY_MATERIAL_CHECK_REJECTED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_QUERIED => Ok(OutputRoute::Queried),
            short_header::OUTPUT_WATCHING => Ok(OutputRoute::Watching),
            short_header::OUTPUT_UNWATCHED => Ok(OutputRoute::Unwatched),
            short_header::OUTPUT_KEY_MATERIAL_CHECKED => Ok(OutputRoute::KeyMaterialChecked),
            short_header::OUTPUT_QUERY_REJECTED => Ok(OutputRoute::QueryRejected),
            short_header::OUTPUT_WATCH_REJECTED => Ok(OutputRoute::WatchRejected),
            short_header::OUTPUT_UNWATCH_REJECTED => Ok(OutputRoute::UnwatchRejected),
            short_header::OUTPUT_KEY_MATERIAL_CHECK_REJECTED => Ok(OutputRoute::KeyMaterialCheckRejected),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

