// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QueryPayload(Selection);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WatchDeploymentsPayload(DeploymentWatch);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WatchCacheRetentionPayload(CacheRetentionWatch);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnwatchPayload(SubscriptionClose);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CheckHostKeyMaterialPayload(KeyMaterialQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QueriedPayload(GenerationListing);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeploymentEventsQueriedPayload(EventLogPage);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRunsQueriedPayload(TestRunListing);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WatchingPayload(SubscriptionOpened);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnwatchedPayload(SubscriptionClosed);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KeyMaterialCheckedPayload(KeyMaterialReport);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QueryRejectedPayload(RejectedQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WatchRejectedPayload(RejectedWatch);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnwatchRejectedPayload(RejectedUnwatch);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KeyMaterialCheckRejectedPayload(RejectedKeyMaterialCheck);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeploymentIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GenerationIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRunIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionToken(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitSequence(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateDigest(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClusterName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NodeName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UserName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClosurePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProposalSource(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FlakeReference(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogPosition(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinLabel(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum GenerationArtifact {
    CompleteHost,
    BaseHost,
    UserEnvironment,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum HostComposition {
    CompleteHost,
    BaseHost,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum HostDeployAction {
    Evaluate,
    Realize,
    SetBootProfile,
    ActivateNow,
    TestActivation,
    ScheduleBootOnce,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UserEnvironmentAction {
    Realize,
    SetProfile,
    ActivateNow,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SourceRevisionPolicy {
    RequireImmutable,
    ResolveAndRecord,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SourceRevisionRecord {
    pub source_revision_policy: SourceRevisionPolicy,
    pub requested_ref: FlakeReference,
    pub resolved_ref: FlakeReference,
    pub string: String,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ActivationEffect {
    LiveActivation,
    BootProfile,
    TestActivation,
    BootOnceProfile,
    ProfileOnly,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum GenerationSlot {
    Current,
    BootPending,
    Rollback,
    Pinned,
    Recent,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TestMode {
    Hermetic,
    Live,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum HostSelection {
    DefaultHost,
    OnHost(NodeName),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Generation {
    pub generation_identifier: GenerationIdentifier,
    pub deployment_identifier: DeploymentIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_artifact: GenerationArtifact,
    pub optional_user_name: Option<UserName>,
    pub activation_effect: ActivationEffect,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
    pub optional_source_revision_record: Option<SourceRevisionRecord>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GenerationListing {
    pub generation_vector: Vec<Generation>,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogPage {
    pub deployment_phase_event_vector: Vec<DeploymentPhaseEvent>,
    pub cache_retention_transition_event_vector: Vec<CacheRetentionTransitionEvent>,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NodeSelector {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub optional_generation_artifact: Option<GenerationArtifact>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GenerationLookup(GenerationIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogRange {
    pub from: EventLogPosition,
    pub until: EventLogPosition,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRunLookup {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub optional_test_run_identifier: Option<TestRunIdentifier>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Selection {
    ByNode(NodeSelector),
    ByGeneration(GenerationLookup),
    ByEventLog(EventLogRange),
    ByTestRun(TestRunLookup),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TestRunPhase {
    Submitted,
    BringingUp,
    Deploying,
    Asserting,
    TearingDown,
    Completed,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TestOutcome {
    Pending,
    Passed,
    Failed(FailureStage),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum FailureStage {
    BringUp,
    Deploy,
    Assert,
    TearDown,
    HermeticCheck,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRunRecord {
    pub test_run_identifier: TestRunIdentifier,
    pub cluster_name: ClusterName,
    pub node: NodeName,
    pub host: NodeName,
    pub test_mode: TestMode,
    pub test_run_phase: TestRunPhase,
    pub test_outcome: TestOutcome,
    pub optional_closure_path: Option<ClosurePath>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRunListing {
    pub test_run_record_vector: Vec<TestRunRecord>,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeploymentWatch {
    pub optional_deployment_identifier: Option<DeploymentIdentifier>,
    pub optional_cluster_name: Option<ClusterName>,
    pub optional_node_name: Option<NodeName>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CacheRetentionWatch {
    pub optional_cluster_name: Option<ClusterName>,
    pub optional_node_name: Option<NodeName>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionClose(SubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionOpened {
    pub subscription_token: SubscriptionToken,
    pub commit_sequence: CommitSequence,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionClosed(SubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KeyMaterialQuery {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub proposal_source: ProposalSource,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum KeyMaterialConcern {
    SecureShellPublicKey,
    YggdrasilPublicKey,
    YggdrasilAddress,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MismatchValue(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OperatorHint(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KeyMaterialMismatch {
    pub key_material_concern: KeyMaterialConcern,
    pub expected: MismatchValue,
    pub actual: MismatchValue,
    pub operator_hint: OperatorHint,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KeyMaterialReport {
    pub node_name: NodeName,
    pub key_material_mismatch_vector: Vec<KeyMaterialMismatch>,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DeploymentPhase {
    Submitted,
    Building,
    Built,
    Copying,
    Activating,
    Activated,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PhaseDetail(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeploymentPhaseEvent {
    pub deployment_identifier: DeploymentIdentifier,
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub deployment_phase: DeploymentPhase,
    pub event_log_position: EventLogPosition,
    pub optional_phase_detail: Option<PhaseDetail>,
    pub optional_source_revision_record: Option<SourceRevisionRecord>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CacheRetentionTransition {
    Pinned,
    Unpinned,
    Promoted,
    Demoted,
    Retired,
    Evicted,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CacheRetentionTransitionEvent {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub cache_retention_transition: CacheRetentionTransition,
    pub generation_slot: GenerationSlot,
    pub optional_generation_slot: Option<GenerationSlot>,
    pub optional_pin_label: Option<PinLabel>,
    pub event_log_position: EventLogPosition,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum QueryRejectionReason {
    GenerationUnknown,
    NodeUnknown,
    EventLogPositionOutOfRange,
    MalformedSelector,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WatchRejectionReason {
    SubscriptionLimitReached,
    MalformedWatch,
    StreamUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnwatchRejectionReason {
    SubscriptionTokenUnknown,
    SubscriptionAlreadyClosed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum KeyMaterialCheckRejectionReason {
    NodeUnknown,
    ProposalSourceUnreachable,
    HostUnreachable,
    PublicationMalformed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedQuery {
    pub query_rejection_reason: QueryRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedWatch(WatchRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedUnwatch {
    pub unwatch_rejection_reason: UnwatchRejectionReason,
    pub subscription_token: SubscriptionToken,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedKeyMaterialCheck {
    pub key_material_check_rejection_reason: KeyMaterialCheckRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Query(QueryPayload),
    WatchDeployments(WatchDeploymentsPayload),
    WatchCacheRetention(WatchCacheRetentionPayload),
    Unwatch(UnwatchPayload),
    CheckHostKeyMaterial(CheckHostKeyMaterialPayload),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Queried(QueriedPayload),
    DeploymentEventsQueried(DeploymentEventsQueriedPayload),
    TestRunsQueried(TestRunsQueriedPayload),
    Watching(WatchingPayload),
    Unwatched(UnwatchedPayload),
    KeyMaterialChecked(KeyMaterialCheckedPayload),
    QueryRejected(QueryRejectedPayload),
    WatchRejected(WatchRejectedPayload),
    UnwatchRejected(UnwatchRejectedPayload),
    KeyMaterialCheckRejected(KeyMaterialCheckRejectedPayload),
}

#[rustfmt::skip]
impl QueryPayload {
    pub fn new(payload: Selection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Selection {
        &self.0
    }
    pub fn into_payload(self) -> Selection {
        self.0
    }
}
#[rustfmt::skip]
impl From<Selection> for QueryPayload {
    fn from(payload: Selection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WatchDeploymentsPayload {
    pub fn new(payload: DeploymentWatch) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeploymentWatch {
        &self.0
    }
    pub fn into_payload(self) -> DeploymentWatch {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeploymentWatch> for WatchDeploymentsPayload {
    fn from(payload: DeploymentWatch) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WatchCacheRetentionPayload {
    pub fn new(payload: CacheRetentionWatch) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CacheRetentionWatch {
        &self.0
    }
    pub fn into_payload(self) -> CacheRetentionWatch {
        self.0
    }
}
#[rustfmt::skip]
impl From<CacheRetentionWatch> for WatchCacheRetentionPayload {
    fn from(payload: CacheRetentionWatch) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnwatchPayload {
    pub fn new(payload: SubscriptionClose) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionClose {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionClose {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionClose> for UnwatchPayload {
    fn from(payload: SubscriptionClose) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CheckHostKeyMaterialPayload {
    pub fn new(payload: KeyMaterialQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &KeyMaterialQuery {
        &self.0
    }
    pub fn into_payload(self) -> KeyMaterialQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<KeyMaterialQuery> for CheckHostKeyMaterialPayload {
    fn from(payload: KeyMaterialQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl QueriedPayload {
    pub fn new(payload: GenerationListing) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GenerationListing {
        &self.0
    }
    pub fn into_payload(self) -> GenerationListing {
        self.0
    }
}
#[rustfmt::skip]
impl From<GenerationListing> for QueriedPayload {
    fn from(payload: GenerationListing) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeploymentEventsQueriedPayload {
    pub fn new(payload: EventLogPage) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EventLogPage {
        &self.0
    }
    pub fn into_payload(self) -> EventLogPage {
        self.0
    }
}
#[rustfmt::skip]
impl From<EventLogPage> for DeploymentEventsQueriedPayload {
    fn from(payload: EventLogPage) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestRunsQueriedPayload {
    pub fn new(payload: TestRunListing) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TestRunListing {
        &self.0
    }
    pub fn into_payload(self) -> TestRunListing {
        self.0
    }
}
#[rustfmt::skip]
impl From<TestRunListing> for TestRunsQueriedPayload {
    fn from(payload: TestRunListing) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WatchingPayload {
    pub fn new(payload: SubscriptionOpened) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionOpened {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionOpened {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionOpened> for WatchingPayload {
    fn from(payload: SubscriptionOpened) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnwatchedPayload {
    pub fn new(payload: SubscriptionClosed) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionClosed {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionClosed {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionClosed> for UnwatchedPayload {
    fn from(payload: SubscriptionClosed) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl KeyMaterialCheckedPayload {
    pub fn new(payload: KeyMaterialReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &KeyMaterialReport {
        &self.0
    }
    pub fn into_payload(self) -> KeyMaterialReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<KeyMaterialReport> for KeyMaterialCheckedPayload {
    fn from(payload: KeyMaterialReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl QueryRejectedPayload {
    pub fn new(payload: RejectedQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedQuery {
        &self.0
    }
    pub fn into_payload(self) -> RejectedQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedQuery> for QueryRejectedPayload {
    fn from(payload: RejectedQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WatchRejectedPayload {
    pub fn new(payload: RejectedWatch) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedWatch {
        &self.0
    }
    pub fn into_payload(self) -> RejectedWatch {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedWatch> for WatchRejectedPayload {
    fn from(payload: RejectedWatch) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnwatchRejectedPayload {
    pub fn new(payload: RejectedUnwatch) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedUnwatch {
        &self.0
    }
    pub fn into_payload(self) -> RejectedUnwatch {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedUnwatch> for UnwatchRejectedPayload {
    fn from(payload: RejectedUnwatch) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl KeyMaterialCheckRejectedPayload {
    pub fn new(payload: RejectedKeyMaterialCheck) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedKeyMaterialCheck {
        &self.0
    }
    pub fn into_payload(self) -> RejectedKeyMaterialCheck {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedKeyMaterialCheck> for KeyMaterialCheckRejectedPayload {
    fn from(payload: RejectedKeyMaterialCheck) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeploymentIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for DeploymentIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GenerationIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for GenerationIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestRunIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TestRunIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscriptionToken {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SubscriptionToken {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommitSequence {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CommitSequence {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StateDigest {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for StateDigest {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ClusterName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ClusterName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NodeName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NodeName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UserName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for UserName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ClosurePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ClosurePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProposalSource {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ProposalSource {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FlakeReference {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for FlakeReference {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EventLogPosition {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for EventLogPosition {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PinLabel {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PinLabel {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GenerationLookup {
    pub fn new(payload: GenerationIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GenerationIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> GenerationIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<GenerationIdentifier> for GenerationLookup {
    fn from(payload: GenerationIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscriptionClose {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionToken> for SubscriptionClose {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscriptionClosed {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionToken> for SubscriptionClosed {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MismatchValue {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MismatchValue {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OperatorHint {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for OperatorHint {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PhaseDetail {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PhaseDetail {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RejectedWatch {
    pub fn new(payload: WatchRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WatchRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> WatchRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<WatchRejectionReason> for RejectedWatch {
    fn from(payload: WatchRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HostSelection {
    pub fn on_host(payload: String) -> Self {
        Self::OnHost(NodeName::new(payload))
    }
}

#[rustfmt::skip]
impl Selection {
    pub fn by_node(payload: NodeSelector) -> Self {
        Self::ByNode(payload)
    }
    pub fn by_generation(payload: GenerationIdentifier) -> Self {
        Self::ByGeneration(GenerationLookup::new(payload))
    }
    pub fn by_event_log(payload: EventLogRange) -> Self {
        Self::ByEventLog(payload)
    }
    pub fn by_test_run(payload: TestRunLookup) -> Self {
        Self::ByTestRun(payload)
    }
}

#[rustfmt::skip]
impl TestOutcome {
    pub fn failed(payload: FailureStage) -> Self {
        Self::Failed(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn query(payload: Selection) -> Self {
        Self::Query(QueryPayload::new(payload))
    }
    pub fn watch_deployments(payload: DeploymentWatch) -> Self {
        Self::WatchDeployments(WatchDeploymentsPayload::new(payload))
    }
    pub fn watch_cache_retention(payload: CacheRetentionWatch) -> Self {
        Self::WatchCacheRetention(WatchCacheRetentionPayload::new(payload))
    }
    pub fn unwatch(payload: SubscriptionClose) -> Self {
        Self::Unwatch(UnwatchPayload::new(payload))
    }
    pub fn check_host_key_material(payload: KeyMaterialQuery) -> Self {
        Self::CheckHostKeyMaterial(CheckHostKeyMaterialPayload::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn queried(payload: GenerationListing) -> Self {
        Self::Queried(QueriedPayload::new(payload))
    }
    pub fn deployment_events_queried(payload: EventLogPage) -> Self {
        Self::DeploymentEventsQueried(DeploymentEventsQueriedPayload::new(payload))
    }
    pub fn test_runs_queried(payload: TestRunListing) -> Self {
        Self::TestRunsQueried(TestRunsQueriedPayload::new(payload))
    }
    pub fn watching(payload: SubscriptionOpened) -> Self {
        Self::Watching(WatchingPayload::new(payload))
    }
    pub fn unwatched(payload: SubscriptionClosed) -> Self {
        Self::Unwatched(UnwatchedPayload::new(payload))
    }
    pub fn key_material_checked(payload: KeyMaterialReport) -> Self {
        Self::KeyMaterialChecked(KeyMaterialCheckedPayload::new(payload))
    }
    pub fn query_rejected(payload: RejectedQuery) -> Self {
        Self::QueryRejected(QueryRejectedPayload::new(payload))
    }
    pub fn watch_rejected(payload: RejectedWatch) -> Self {
        Self::WatchRejected(WatchRejectedPayload::new(payload))
    }
    pub fn unwatch_rejected(payload: RejectedUnwatch) -> Self {
        Self::UnwatchRejected(UnwatchRejectedPayload::new(payload))
    }
    pub fn key_material_check_rejected(payload: RejectedKeyMaterialCheck) -> Self {
        Self::KeyMaterialCheckRejected(KeyMaterialCheckRejectedPayload::new(payload))
    }
}

#[rustfmt::skip]
impl From<NodeName> for HostSelection {
    fn from(payload: NodeName) -> Self {
        Self::OnHost(payload)
    }
}

#[rustfmt::skip]
impl From<NodeSelector> for Selection {
    fn from(payload: NodeSelector) -> Self {
        Self::ByNode(payload)
    }
}

#[rustfmt::skip]
impl From<GenerationLookup> for Selection {
    fn from(payload: GenerationLookup) -> Self {
        Self::ByGeneration(payload)
    }
}

#[rustfmt::skip]
impl From<EventLogRange> for Selection {
    fn from(payload: EventLogRange) -> Self {
        Self::ByEventLog(payload)
    }
}

#[rustfmt::skip]
impl From<TestRunLookup> for Selection {
    fn from(payload: TestRunLookup) -> Self {
        Self::ByTestRun(payload)
    }
}

#[rustfmt::skip]
impl From<FailureStage> for TestOutcome {
    fn from(payload: FailureStage) -> Self {
        Self::Failed(payload)
    }
}

#[rustfmt::skip]
impl From<QueryPayload> for Input {
    fn from(payload: QueryPayload) -> Self {
        Self::Query(payload)
    }
}

#[rustfmt::skip]
impl From<WatchDeploymentsPayload> for Input {
    fn from(payload: WatchDeploymentsPayload) -> Self {
        Self::WatchDeployments(payload)
    }
}

#[rustfmt::skip]
impl From<WatchCacheRetentionPayload> for Input {
    fn from(payload: WatchCacheRetentionPayload) -> Self {
        Self::WatchCacheRetention(payload)
    }
}

#[rustfmt::skip]
impl From<UnwatchPayload> for Input {
    fn from(payload: UnwatchPayload) -> Self {
        Self::Unwatch(payload)
    }
}

#[rustfmt::skip]
impl From<CheckHostKeyMaterialPayload> for Input {
    fn from(payload: CheckHostKeyMaterialPayload) -> Self {
        Self::CheckHostKeyMaterial(payload)
    }
}

#[rustfmt::skip]
impl From<QueriedPayload> for Output {
    fn from(payload: QueriedPayload) -> Self {
        Self::Queried(payload)
    }
}

#[rustfmt::skip]
impl From<DeploymentEventsQueriedPayload> for Output {
    fn from(payload: DeploymentEventsQueriedPayload) -> Self {
        Self::DeploymentEventsQueried(payload)
    }
}

#[rustfmt::skip]
impl From<TestRunsQueriedPayload> for Output {
    fn from(payload: TestRunsQueriedPayload) -> Self {
        Self::TestRunsQueried(payload)
    }
}

#[rustfmt::skip]
impl From<WatchingPayload> for Output {
    fn from(payload: WatchingPayload) -> Self {
        Self::Watching(payload)
    }
}

#[rustfmt::skip]
impl From<UnwatchedPayload> for Output {
    fn from(payload: UnwatchedPayload) -> Self {
        Self::Unwatched(payload)
    }
}

#[rustfmt::skip]
impl From<KeyMaterialCheckedPayload> for Output {
    fn from(payload: KeyMaterialCheckedPayload) -> Self {
        Self::KeyMaterialChecked(payload)
    }
}

#[rustfmt::skip]
impl From<QueryRejectedPayload> for Output {
    fn from(payload: QueryRejectedPayload) -> Self {
        Self::QueryRejected(payload)
    }
}

#[rustfmt::skip]
impl From<WatchRejectedPayload> for Output {
    fn from(payload: WatchRejectedPayload) -> Self {
        Self::WatchRejected(payload)
    }
}

#[rustfmt::skip]
impl From<UnwatchRejectedPayload> for Output {
    fn from(payload: UnwatchRejectedPayload) -> Self {
        Self::UnwatchRejected(payload)
    }
}

#[rustfmt::skip]
impl From<KeyMaterialCheckRejectedPayload> for Output {
    fn from(payload: KeyMaterialCheckRejectedPayload) -> Self {
        Self::KeyMaterialCheckRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_QUERY: u64 = 0x0000000000000000;
    pub const INPUT_WATCH_DEPLOYMENTS: u64 = 0x0001000000000000;
    pub const INPUT_WATCH_CACHE_RETENTION: u64 = 0x0002000000000000;
    pub const INPUT_UNWATCH: u64 = 0x0003000000000000;
    pub const INPUT_CHECK_HOST_KEY_MATERIAL: u64 = 0x0004000000000000;
    pub const OUTPUT_QUERIED: u64 = 0x0100000000000000;
    pub const OUTPUT_DEPLOYMENT_EVENTS_QUERIED: u64 = 0x0101000000000000;
    pub const OUTPUT_TEST_RUNS_QUERIED: u64 = 0x0102000000000000;
    pub const OUTPUT_WATCHING: u64 = 0x0103000000000000;
    pub const OUTPUT_UNWATCHED: u64 = 0x0104000000000000;
    pub const OUTPUT_KEY_MATERIAL_CHECKED: u64 = 0x0105000000000000;
    pub const OUTPUT_QUERY_REJECTED: u64 = 0x0106000000000000;
    pub const OUTPUT_WATCH_REJECTED: u64 = 0x0107000000000000;
    pub const OUTPUT_UNWATCH_REJECTED: u64 = 0x0108000000000000;
    pub const OUTPUT_KEY_MATERIAL_CHECK_REJECTED: u64 = 0x0109000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Query,
    WatchDeployments,
    WatchCacheRetention,
    Unwatch,
    CheckHostKeyMaterial,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Queried,
    DeploymentEventsQueried,
    TestRunsQueried,
    Watching,
    Unwatched,
    KeyMaterialChecked,
    QueryRejected,
    WatchRejected,
    UnwatchRejected,
    KeyMaterialCheckRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Query(_) => InputRoute::Query,
            Self::WatchDeployments(_) => InputRoute::WatchDeployments,
            Self::WatchCacheRetention(_) => InputRoute::WatchCacheRetention,
            Self::Unwatch(_) => InputRoute::Unwatch,
            Self::CheckHostKeyMaterial(_) => InputRoute::CheckHostKeyMaterial,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::WatchDeployments(_) => short_header::INPUT_WATCH_DEPLOYMENTS,
            Self::WatchCacheRetention(_) => short_header::INPUT_WATCH_CACHE_RETENTION,
            Self::Unwatch(_) => short_header::INPUT_UNWATCH,
            Self::CheckHostKeyMaterial(_) => short_header::INPUT_CHECK_HOST_KEY_MATERIAL,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_QUERY => Ok(InputRoute::Query),
            short_header::INPUT_WATCH_DEPLOYMENTS => Ok(InputRoute::WatchDeployments),
            short_header::INPUT_WATCH_CACHE_RETENTION => {
                Ok(InputRoute::WatchCacheRetention)
            }
            short_header::INPUT_UNWATCH => Ok(InputRoute::Unwatch),
            short_header::INPUT_CHECK_HOST_KEY_MATERIAL => {
                Ok(InputRoute::CheckHostKeyMaterial)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Queried(_) => OutputRoute::Queried,
            Self::DeploymentEventsQueried(_) => OutputRoute::DeploymentEventsQueried,
            Self::TestRunsQueried(_) => OutputRoute::TestRunsQueried,
            Self::Watching(_) => OutputRoute::Watching,
            Self::Unwatched(_) => OutputRoute::Unwatched,
            Self::KeyMaterialChecked(_) => OutputRoute::KeyMaterialChecked,
            Self::QueryRejected(_) => OutputRoute::QueryRejected,
            Self::WatchRejected(_) => OutputRoute::WatchRejected,
            Self::UnwatchRejected(_) => OutputRoute::UnwatchRejected,
            Self::KeyMaterialCheckRejected(_) => OutputRoute::KeyMaterialCheckRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Queried(_) => short_header::OUTPUT_QUERIED,
            Self::DeploymentEventsQueried(_) => {
                short_header::OUTPUT_DEPLOYMENT_EVENTS_QUERIED
            }
            Self::TestRunsQueried(_) => short_header::OUTPUT_TEST_RUNS_QUERIED,
            Self::Watching(_) => short_header::OUTPUT_WATCHING,
            Self::Unwatched(_) => short_header::OUTPUT_UNWATCHED,
            Self::KeyMaterialChecked(_) => short_header::OUTPUT_KEY_MATERIAL_CHECKED,
            Self::QueryRejected(_) => short_header::OUTPUT_QUERY_REJECTED,
            Self::WatchRejected(_) => short_header::OUTPUT_WATCH_REJECTED,
            Self::UnwatchRejected(_) => short_header::OUTPUT_UNWATCH_REJECTED,
            Self::KeyMaterialCheckRejected(_) => {
                short_header::OUTPUT_KEY_MATERIAL_CHECK_REJECTED
            }
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_QUERIED => Ok(OutputRoute::Queried),
            short_header::OUTPUT_DEPLOYMENT_EVENTS_QUERIED => {
                Ok(OutputRoute::DeploymentEventsQueried)
            }
            short_header::OUTPUT_TEST_RUNS_QUERIED => Ok(OutputRoute::TestRunsQueried),
            short_header::OUTPUT_WATCHING => Ok(OutputRoute::Watching),
            short_header::OUTPUT_UNWATCHED => Ok(OutputRoute::Unwatched),
            short_header::OUTPUT_KEY_MATERIAL_CHECKED => {
                Ok(OutputRoute::KeyMaterialChecked)
            }
            short_header::OUTPUT_QUERY_REJECTED => Ok(OutputRoute::QueryRejected),
            short_header::OUTPUT_WATCH_REJECTED => Ok(OutputRoute::WatchRejected),
            short_header::OUTPUT_UNWATCH_REJECTED => Ok(OutputRoute::UnwatchRejected),
            short_header::OUTPUT_KEY_MATERIAL_CHECK_REJECTED => {
                Ok(OutputRoute::KeyMaterialCheckRejected)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Query",
        "WatchDeployments",
        "WatchCacheRetention",
        "Unwatch",
        "CheckHostKeyMaterial",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
